# Set the language Travis CI should expect.
language: node_js

# Set the Node.js version you’d like Travis to use. Add more versions as you like.
node_js:
- 17

# Cache all npm dependencies so Travis CI only installs dependencies once.
# For multiple builds, caching all npm dependencies enables your builds to run faster.
cache: npm

# Configure the build cycles to tell Travis CI to install all dependencies.
# You can also add other dependencies you like Travis to install globally.
install: # Hook provided by Travis CI
- npm install

# Tell Travis CI to run the test for your Node application
script:
- npm test

# # The default for ubuntu 20.04
# dist:
# - focal

# services: 
# - docker

# before_install:
# - docker build -t forethought .
# - docker run -d -p 8080:8080 forethought
# - docker ps -a 

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key: HEROKU_API_KEY
  app: CICDDemo